services:
  db:
    image: postgres
    container_name: rental_postgres
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./rental-manager-api
    container_name: rental_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: rental-manager-api
      # PostgreSQL DB config
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rental_db
      SPRING_DATASOURCE_USERNAME: rental_user
      SPRING_DATASOURCE_PASSWORD: rental_pass
      # JPA config
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      # Backend server
      SERVER_PORT: 8080

  frontend:
    build:
      context: ./rental-manager-ui
    container_name: rental_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
