services:
  db:
    image: postgres
    container_name: rental_postgres
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./api
    container_name: rental_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # DB config
      JDBC_PREFIX: jdbc
      DB_PROTOCOL: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rental_db
      DB_USERNAME: rental_user
      DB_PASSWORD: rental_pass
      # JPA config
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "true"
      # Backend server
      SERVER_PORT: 8080
      FRONTEND_URL: http://localhost:3000

  frontend:
    build:
      context: ./ui
    container_name: rental_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
